language: python
sudo: false
cache: pip
python:
  - "2.7"
# command to install dependencies
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install pipenv
# command to run tests
script:
  - pipenv install
  - pipenv run -- py.test tests -s -v